<a href="https://colab.research.google.com/github/25janet/Alx_Data_Engineering_Python/blob/main/Introduction_to_NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Exercise.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Exercise: Introduction to NumPy


In this notebook, we explore the fundamentals of NumPy for efficient data manipulation and analysis in Python.


## Learning objectives

In this train, we will learn:
- How to create, reshape, and manipulate arrays using NumPy.
- How to access and modify elements in NumPy arrays.
- How to apply key NumPy functions to analyse real-world problems.

## Exercises

In [1]:
import numpy as np

### Exercise 1

Given a 2D NumPy array, `pollution_data`, representing daily air quality index values of a city for a week (rows for days and columns for different pollutants), write a code snippet to return the day (row) with the highest average pollution level.

In [3]:
pollution_data = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])
print(pollution_data)

[[45 65 70]
 [55 60 50]
 [60 58 67]]


In [6]:
# insert code here
daily_avg = pollution_data.mean(axis = 1)
print(daily_avg)
highest_day = np.argmax(daily_avg)
print(f"Day with the highest average pollution level is:{highest_day}")

[60.         55.         61.66666667]
Day with the highest average pollution level is:2


### Exercise 2

A forest department is monitoring deforestation by analysing satellite data of five similarly sized regions. When the monitoring started, each region had full forest coverage (i.e. 100). The most recent data collected has been stored in a 1D NumPy array, `forest_coverage`, where each element represents the percentage of forest cover in different regions. Write code to calculate the total percentage of coverage **lost**, if each 1% reduction in forest cover equals 100 square kilometres.

In [8]:
forest_coverage = np.array([70, 80, 65, 90, 85])


In [15]:
# insert code here
loss = 100 - forest_coverage
print(loss)
total_loss = np.sum(loss)
print(total_loss)
total_area_lost = total_loss * 100
print(f'Total forest area lost is {total_area_lost} squared km')

[30 20 35 10 15]
110
Total forest area lost is 11000 squared km


### Exercise 3

For a study on water conservation, we have a 2D NumPy array, `water_quality`, representing different water quality parameters (columns) for various water bodies (rows). Write code to find the water body index (row index) with the worst average quality parameter.

In [16]:
water_quality = np.array([[7.8, 6.5, 8.0], [5.4, 7.2, 6.5]])
print(water_quality)

[[7.8 6.5 8. ]
 [5.4 7.2 6.5]]


In [20]:
# insert code here
average_water_quality = water_quality.mean(axis = 1)
print(average_water_quality)
worst_avg_quality = average_water_quality.argmin()
print(worst_avg_quality)
print(f"The water body with the worst average water quality is {worst_avg_quality}")

[7.43333333 6.36666667]
1
The water body with the worst average water quality is 1


### Exercise 4

Biologists tracking caracal movement have recorded the number of caracals spotted in different regions in a 2D NumPy array, `animal_sightings`. Each row represents a different region, and columns represent different days. Write a code snippet to find the index of the region with the highest average number of sightings.

In [22]:
animal_sightings = np.array([[5, 7, 8], [3, 4, 6], [9, 10, 7]])

In [24]:
# insert code here
average_number_sightings = animal_sightings.mean(axis = 1)
print(average_number_sightings)
highest_avg_sightings = average_number_sightings.argmax()
print(highest_avg_sightings)

[6.66666667 4.33333333 8.66666667]
2


### Exercise 5

`np.reshape()` allows us to change the shape of an array without changing its data. For example, we can reshape a 1D array into a 2D array (matrix) or vice versa, as long as the total number of elements remains the same. Remember to read more about functions in the NumPy documentation if anything is unclear.

Biologists have collected data on bird sightings in a region over a month, stored in a 1D NumPy array where each element represents the number of sightings on a particular day. Reshape this data into a 2D array (matrix) representing weeks and days (assume 4 weeks in a month, 7 days per week), and calculate the total sightings for each week.

In [27]:
bird_sightings = np.array([3, 4, 2, 5, 1, 0, 4, 3, 5, 2, 1, 7, 8, 1, 2, 3, 4, 1, 0, 5, 6, 2, 3, 4, 1, 4, 6, 7])

In [30]:
# insert code here
reshaped_bird_sightings = bird_sightings.reshape(4,7)
total_sightings_per_week = reshaped_bird_sightings.sum(axis = 1)
print(total_sightings_per_week)

[19 27 21 27]


### Exercise 6

`np.transpose()` is a NumPy function that flips a matrix over its diagonal, switching the row and column indices of the array. This means that the first row becomes the first column, the second row becomes the second column, and so on.

Meteorologists have recorded temperature and precipitation data over a year in a 2D array (rows for months, columns for temperature and precipitation). Transpose the array so that rows represent temperature and precipitation, and columns represent months. Then calculate the average temperature and precipitation over the year.

In [31]:
climate_data = np.array([[22, 50], [25, 43], [28, 35], [30, 20], [27, 25], [25, 30], [23, 40], [24, 55], [22, 60], [20, 65], [18, 70], [22, 58]])

In [36]:
# insert code here
transposed_climate_data = climate_data.transpose()
print(transposed_climate_data)
avg_temp = transposed_climate_data[0].mean()
avg_prec = transposed_climate_data[1].mean()
print(avg_temp)
print(avg_prec)


[[22 25 28 30 27 25 23 24 22 20 18 22]
 [50 43 35 20 25 30 40 55 60 65 70 58]]
23.833333333333332
45.916666666666664


## Solutions

### Exercise 1

`pollution_data.mean(axis=1)` calculates the average pollution level for each day (row). `np.argmax` finds the index of the day with the highest average pollution level.

In [ ]:
import numpy as np

In [ ]:
pollution_data = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])

most_polluted_day_index = np.argmax(pollution_data.mean(axis=1))

print(pollution_data[most_polluted_day_index])

### Exercise 2

`100 - forest_coverage` calculates the proportion of deforestation for each region. Summing these loss values and multiplying them by 100 (conversion to square kilometres) gives the total forest cover lost in square kilometres.


In [ ]:
forest_coverage = np.array([70, 80, 65, 90, 85])

total_forest_cover_lost = (100 - forest_coverage).sum() * 100

print(total_forest_cover_lost)

### Exercise 3

`water_quality.mean(axis=1)` computes the average quality parameter for each water body (row). `np.argmin` finds the index of the water body with the worst average quality.


In [21]:
water_quality = np.array([[7.8, 6.5, 8.0], [5.4, 7.2, 6.5]])

worst_water_quality_index = np.argmin(water_quality.mean(axis=1))

print(worst_water_quality_index)

1


### Exercise 4

`animal_sightings.mean(axis=1)` computes the average number of sightings per region. `np.argmax` finds the index of the region with the highest average.


In [25]:
animal_sightings = np.array([[5, 7, 8], [3, 4, 6], [9, 10, 7]])

highest_sightings_region_index = np.argmax(animal_sightings.mean(axis=1))

print(highest_sightings_region_index)

2


### Exercise 5

The `reshape(4, 7)` function reshapes the 1D array into a 2D array with 4 rows (weeks) and 7 columns (days). `sum(axis=1)` calculates the sum along the rows (each week), providing the total bird sightings per week.


In [ ]:
bird_sightings = np.array([3, 4, 2, 5, 1, 0, 4, 3, 5, 2, 1, 7, 8, 1, 2, 3, 4, 1, 0, 5, 6, 2, 3, 4, 1, 4, 6, 7])

reshaped_sightings = bird_sightings.reshape(4, 7)
total_sightings_per_week = reshaped_sightings.sum(axis=1)

print(total_sightings_per_week)

### Exercise 6

`transpose()` changes the shape of `climate_data` so that rows and columns are swapped. Now, the first row represents temperatures and the second row represents precipitation for each month. The `mean()` function calculates the average value for each of these rows, giving the average temperature and precipitation over the year.


In [37]:
climate_data = np.array([[22, 50], [25, 43], [28, 35], [30, 20], [27, 25], [25, 30], [23, 40], [24, 55], [22, 60], [20, 65], [18, 70], [22, 58]])

transposed_climate_data = climate_data.transpose()
print(transposed_climate_data)

average_temperature = transposed_climate_data[0].mean()
average_precipitation = transposed_climate_data[1].mean()

print(average_temperature)
print(average_precipitation)

[[22 25 28 30 27 25 23 24 22 20 18 22]
 [50 43 35 20 25 30 40 55 60 65 70 58]]
23.833333333333332
45.916666666666664


#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>